<a href="https://colab.research.google.com/github/mlabiunda/1erentrega-dataC/blob/main/Notebook5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programa Ingenias+ Data Science

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [1]:
#Importar numpy
import numpy as np

In [3]:
#Ejercicio 1: Crear un arreglo de ceros de longitud 12
array_ceros=np.zeros(12)
print(array_ceros)
len (array_ceros)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


12

In [5]:
#prueba: arreglo de unos de longitud 5
array_unos=np.ones(5)
print(array_unos)


[1. 1. 1. 1. 1.]


In [6]:
#Ejercicio 2: Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
array_diez=np.zeros(10)
array_diez[5]=10
print(array_diez)

[ 0.  0.  0.  0.  0. 10.  0.  0.  0.  0.]


In [8]:
#prueba 2: en el arreglo de unos, que la tercer posicion tenga un 7
array_unos[3]=7
print(array_unos)

[1. 1. 1. 7. 1.]


In [10]:
#Ejercicio 3: Crear un arreglo que tenga los números del 10 al 49
array_10_49=np.arange(10,50)
print(array_10_49)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [12]:
#pruba 3: crear arreglo del 11 al 38 (tengo que escribir hasta el 39 porque el ultimo no lo incluye)
array_11_38=np.arange(11,39)
print(array_11_38)

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38]


In [14]:
#Ejercicio 4: Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
array_8_10=np.arange(9).reshape(3,3)
print(array_8_10)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [15]:
#prueba 4: arreglo 2d de shape 4,4 que tenga los numeros de 16 al 32 (como es arreglo de 4 x 4 tiene ue tener 16 numeros, toma el ultimo)
array_16_32=np.arange(16,32).reshape(4,4)
print(array_16_32)

[[16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [16]:
#Ejercicio 5: Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
array_100=np.random.rand(100)
print(array_100)

[0.29573438 0.63350618 0.49919192 0.0629795  0.13097469 0.24028438
 0.63526755 0.04403344 0.82149993 0.93221447 0.68432642 0.21688874
 0.45126188 0.27662433 0.55243096 0.53453617 0.49619391 0.80689673
 0.98944319 0.7455189  0.4902488  0.04958154 0.63841394 0.92637319
 0.41019275 0.50362647 0.12818819 0.41691754 0.94181471 0.0690028
 0.01896718 0.1148164  0.26788197 0.83539539 0.54589328 0.73935036
 0.24517331 0.97590773 0.0795691  0.38409452 0.66837386 0.51723465
 0.4951308  0.16902526 0.12117139 0.55412459 0.27474674 0.46691741
 0.77510949 0.55488604 0.35775504 0.54240917 0.32200252 0.90348121
 0.01267468 0.03846274 0.53171067 0.92307537 0.8683432  0.89704954
 0.02377148 0.8737506  0.21779326 0.51380494 0.78147481 0.88450202
 0.907959   0.74755416 0.92621584 0.72174586 0.50810216 0.08035964
 0.81732452 0.03706371 0.39807747 0.27860341 0.25436923 0.7723583
 0.55778337 0.66659443 0.20398609 0.49708006 0.61367569 0.5539296
 0.55982385 0.21712969 0.18453282 0.0034445  0.74634251 0.1921266

In [17]:
array_media=np.mean(array_100)
print(array_media)
array_varianza=np.var(array_100)
print(array_varianza)

0.46880612618763223
0.08529241586797465


In [19]:
#pruba 5: crear arreglo de 50 numeros aleatorios y calcular media y varianza
array_50=np.random.rand(50)
print(array_50)
array_media50=np.mean(array_50)
print(array_media50)
array_varianza50=np.var(array_50)
print(array_varianza50)

[0.91443413 0.17503227 0.809252   0.14420445 0.24876922 0.73668782
 0.94698635 0.13209667 0.58752223 0.98632899 0.39839743 0.75530011
 0.91034637 0.05463221 0.09682439 0.83472894 0.24732669 0.34772996
 0.13744203 0.66689167 0.15661216 0.17343304 0.59176842 0.83414155
 0.61485155 0.85690557 0.32386676 0.10905796 0.97940431 0.39528657
 0.60467974 0.83593274 0.09112459 0.21219748 0.11959399 0.6822463
 0.3463422  0.52036197 0.23434211 0.25651436 0.01004311 0.57354527
 0.35988366 0.51006113 0.97754631 0.4703708  0.80077289 0.82721494
 0.24043193 0.62084054]
0.489206158080658
0.09089023897380662


In [21]:
#Ejercicio 6: Calcular la media de un arreglo usando np.sum
array_100_sum=np.sum(array_100)/[len(array_100)]
print(array_100_sum)

[0.46880613]


In [22]:
#prueba6: la media es la suma de x0 a xn dividido n
array_50_sum=np.sum(array_50)/[len(array_50)]
print(array_50_sum)

[0.48920616]


In [23]:
#ejercicio 7

In [24]:
array_100_varianza=np.sum((array_100-np.mean(array_100))**2)/[len(array_100)]
print(array_100_varianza)

[0.08529242]


In [25]:
#prueba7: la varianza es la sumatoria de (Xi-xmedia)² / (n-1)
array_50_varianza=np.sum((array_50-np.mean(array_50))**2)/len(array_50)
print(array_50_varianza)

0.09089023897380662


In [26]:
#Ejercicio8
#Crear un array de números aleatorios usando np.random.randn.

In [27]:
#Crear un array de números aleatorios usando np.random.randn.
array_aletorio=np.random.rand(5)
print(array_aletorio)

[0.06820107 0.80269364 0.46439282 0.43309887 0.52649206]


In [29]:
array_aleatorio_8=np.random.rand(8)
print(array_aleatorio_8)

[0.99425719 0.23530587 0.31864975 0.30111426 0.77809041 0.307768
 0.91894648 0.70535525]
